// <auto-generated />
using System;
using BankStatementParsing.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankStatementParsing.Infrastructure.Migrations
{
    [DbContext(typeof(BankStatementParsingContext))]
    [Migration("20250629134810_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("BIC")
                        .HasColumnType("TEXT");

                    b.Property<string>("BankCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Contact")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Holder")
                        .HasColumnType("TEXT");

                    b.Property<string>("IBAN")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Merchant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("MerchantIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Merchants");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.MerchantTag", b =>
                {
                    b.Property<int>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MerchantId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("MerchantTags");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Statement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ClosingBalance")
                        .HasColumnType("REAL");

                    b.Property<int?>("NumCredits")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NumDebits")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("OpeningBalance")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatementNumber")
                        .HasColumnType("TEXT");

                    b.Property<double?>("TotalCredits")
                        .HasColumnType("REAL");

                    b.Property<double?>("TotalDebits")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Statements");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<double?>("Countervalue")
                        .HasColumnType("REAL");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ExchangeRate")
                        .HasColumnType("REAL");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MerchantId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MerchantId");

                    b.HasIndex("StatementId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.TransactionTag", b =>
                {
                    b.Property<int>("TransactionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("TransactionTags");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.MerchantTag", b =>
                {
                    b.HasOne("BankStatementParsing.Infrastructure.Merchant", "Merchant")
                        .WithMany("MerchantTags")
                        .HasForeignKey("MerchantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankStatementParsing.Infrastructure.Tag", "Tag")
                        .WithMany("MerchantTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Statement", b =>
                {
                    b.HasOne("BankStatementParsing.Infrastructure.Account", "Account")
                        .WithMany("Statements")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Transaction", b =>
                {
                    b.HasOne("BankStatementParsing.Infrastructure.Merchant", "Merchant")
                        .WithMany("Transactions")
                        .HasForeignKey("MerchantId");

                    b.HasOne("BankStatementParsing.Infrastructure.Statement", "Statement")
                        .WithMany("Transactions")
                        .HasForeignKey("StatementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Merchant");

                    b.Navigation("Statement");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.TransactionTag", b =>
                {
                    b.HasOne("BankStatementParsing.Infrastructure.Tag", "Tag")
                        .WithMany("TransactionTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankStatementParsing.Infrastructure.Transaction", "Transaction")
                        .WithMany("TransactionTags")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Account", b =>
                {
                    b.Navigation("Statements");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Merchant", b =>
                {
                    b.Navigation("MerchantTags");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Statement", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Tag", b =>
                {
                    b.Navigation("MerchantTags");

                    b.Navigation("TransactionTags");
                });

            modelBuilder.Entity("BankStatementParsing.Infrastructure.Transaction", b =>
                {
                    b.Navigation("TransactionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
